version: "3"

vars:
  GREETING: Hello, Digital Business patrons!

tasks:
    default:
        cmds:
        - echo "{{.GREETING}}"
        silent: true

    build-web:
        desc: Build the web application
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/businessctl client.go 
        - GOFLAGS=-mod=mod go build -o bin/businesssvr server.go 

    build-desktop:
        desc: Build the desktop application for current OS
        cmds:
        - guiutl package -os macos -icon business.png
        - guiutl package -os linux -icon business.png
        - guiutl package -os windows -icon business.png

    package-android:
        desc: Package the mobile application for Android
        cmds:
        - guiutl package -os android -appID net.bhojpur.business -icon business.png

    package-ios:
        desc: Package the mobile application for iOS
        cmds:
        - guiutl package -os ios -appID net.bhojpur.business -icon business.png

    release-macos:
        desc: Release the native application for macOS App Store
        cmds:
        - guiutl release -appID net.bhojpur.business -appVersion 1.0 -appBuild 1 -category business

    release-android:
        desc: Release the mobile application for Google Play
        cmds:
        - guiutl release -os android -appID net.bhojpur.business -appVersion 1.0 -appBuild 1

    release-ios:
        desc: Release the mobile application for iOS App Store
        cmds:
        - guiutl release -os ios -appID net.bhojpur.business -appVersion 1.0 -appBuild 1

    run-web-server:
        desc: Run the web server application from source code
        cmds:
        - GOFLAGS=-mod=mod go run server.go
 
    run-web-client:
        desc: Run the web client application from source code
        cmds:
        - GOFLAGS=-mod=mod go run client.go

    run-mobile:
        desc: Run the mobile client application on emulator
        cmds:
        - GOFLAGS=-mod=mod go run -tags mobile native/main.go

    run-desktop: 
        desc: Run the desktop application on local host
        cmds:
        - GOFLAGS=-mod=mod go run native/main.go

    generate-js:
        desc: Generate Javascript source code (using brew install protoc-gen-grpc-web) from Protocol Buffers
        cmds:
        - mkdir -p js
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --js_out=import_style=commonjs:./js --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./js pkg/api/v1/users/*.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --js_out=import_style=commonjs:./js --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./js pkg/api/v1/inventories/*.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --js_out=import_style=commonjs:./js --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./js pkg/api/v1/purchases/*.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --js_out=import_style=commonjs:./js --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./js pkg/api/v1/sales/*.proto

    generate-go:
        desc: Generate Go source code from Protocol Buffers
        cmds:
        - mkdir -p api/v1
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --go_out=./api/v1 --go_opt=module=github.com/bhojpur/digital-business/api/v1 pkg/api/v1/users/*.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --go-grpc_out=./api/v1 --go-grpc_opt=module=github.com/bhojpur/digital-business/api/v1 pkg/api/v1/users/*.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --go_out=./api/v1 --go_opt=module=github.com/bhojpur/digital-business/api/v1 pkg/api/v1/inventories/*.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --go-grpc_out=./api/v1 --go-grpc_opt=module=github.com/bhojpur/digital-business/api/v1 pkg/api/v1/inventories/*.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --go_out=./api/v1 --go_opt=module=github.com/bhojpur/digital-business/api/v1 pkg/api/v1/purchases/*.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --go-grpc_out=./api/v1 --go-grpc_opt=module=github.com/bhojpur/digital-business/api/v1 pkg/api/v1/purchases/*.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --go_out=./api/v1 --go_opt=module=github.com/bhojpur/digital-business/api/v1 pkg/api/v1/sales/*.proto
        - protoc --proto_path=. --proto_path=$GOPATH/src/github.com/gogo/protobuf --go-grpc_out=./api/v1 --go-grpc_opt=module=github.com/bhojpur/digital-business/api/v1 pkg/api/v1/sales/*.proto

    test:
        desc: Execute all the Unit Tests
        cmds:
        - gotestsum --junitfile test-results/unit-tests.xml -- -short -race -cover -coverprofile test-results/cover.out ./...

    swagger.gen:
        desc: Generate Go code
        cmds:
        - GOFLAGS=-mod=mod go generate bhojpur.net/business/internal bhojpur.net/business/pkg/swagger

    swagger.validate:
        desc: Validate all the Swagger API specifications
        cmds:
        - swagger validate pkg/swagger/swagger.yml

    swagger.doc:
        desc: Generate documentation for Swagger specified APIs
        cmds:
        - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html