// source: pkg/api/v1/inventories/delivery_return_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var pkg_api_v1_inventories_delivery_return_detail_message_pb = require('../../../../pkg/api/v1/inventories/delivery_return_detail_message_pb.js');
goog.object.extend(proto, pkg_api_v1_inventories_delivery_return_detail_message_pb);
var pkg_api_v1_inventories_delivery_message_pb = require('../../../../pkg/api/v1/inventories/delivery_message_pb.js');
goog.object.extend(proto, pkg_api_v1_inventories_delivery_message_pb);
goog.exportSymbol('proto.v1.inventories.DeliveryReturn', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v1.inventories.DeliveryReturn = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.v1.inventories.DeliveryReturn.repeatedFields_, null);
};
goog.inherits(proto.v1.inventories.DeliveryReturn, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v1.inventories.DeliveryReturn.displayName = 'proto.v1.inventories.DeliveryReturn';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.v1.inventories.DeliveryReturn.repeatedFields_ = [13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v1.inventories.DeliveryReturn.prototype.toObject = function(opt_includeInstance) {
  return proto.v1.inventories.DeliveryReturn.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v1.inventories.DeliveryReturn} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.inventories.DeliveryReturn.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    companyId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    branchId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    branchName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    delivery: (f = msg.getDelivery()) && pkg_api_v1_inventories_delivery_message_pb.Delivery.toObject(includeInstance, f),
    code: jspb.Message.getFieldWithDefault(msg, 6, ""),
    returnDate: jspb.Message.getFieldWithDefault(msg, 7, ""),
    remark: jspb.Message.getFieldWithDefault(msg, 8, ""),
    createdAt: jspb.Message.getFieldWithDefault(msg, 9, ""),
    createdBy: jspb.Message.getFieldWithDefault(msg, 10, ""),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 11, ""),
    updatedBy: jspb.Message.getFieldWithDefault(msg, 12, ""),
    detailsList: jspb.Message.toObjectList(msg.getDetailsList(),
    pkg_api_v1_inventories_delivery_return_detail_message_pb.DeliveryReturnDetail.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v1.inventories.DeliveryReturn}
 */
proto.v1.inventories.DeliveryReturn.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v1.inventories.DeliveryReturn;
  return proto.v1.inventories.DeliveryReturn.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v1.inventories.DeliveryReturn} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v1.inventories.DeliveryReturn}
 */
proto.v1.inventories.DeliveryReturn.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompanyId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBranchId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBranchName(value);
      break;
    case 5:
      var value = new pkg_api_v1_inventories_delivery_message_pb.Delivery;
      reader.readMessage(value,pkg_api_v1_inventories_delivery_message_pb.Delivery.deserializeBinaryFromReader);
      msg.setDelivery(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setReturnDate(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setRemark(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedAt(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedBy(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedAt(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedBy(value);
      break;
    case 13:
      var value = new pkg_api_v1_inventories_delivery_return_detail_message_pb.DeliveryReturnDetail;
      reader.readMessage(value,pkg_api_v1_inventories_delivery_return_detail_message_pb.DeliveryReturnDetail.deserializeBinaryFromReader);
      msg.addDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v1.inventories.DeliveryReturn.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v1.inventories.DeliveryReturn.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v1.inventories.DeliveryReturn} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v1.inventories.DeliveryReturn.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCompanyId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBranchId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBranchName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDelivery();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      pkg_api_v1_inventories_delivery_message_pb.Delivery.serializeBinaryToWriter
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getReturnDate();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getRemark();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCreatedAt();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCreatedBy();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getUpdatedBy();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getDetailsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      pkg_api_v1_inventories_delivery_return_detail_message_pb.DeliveryReturnDetail.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string company_id = 2;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getCompanyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setCompanyId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string branch_id = 3;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getBranchId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setBranchId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string branch_name = 4;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getBranchName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setBranchName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional Delivery delivery = 5;
 * @return {?proto.v1.inventories.Delivery}
 */
proto.v1.inventories.DeliveryReturn.prototype.getDelivery = function() {
  return /** @type{?proto.v1.inventories.Delivery} */ (
    jspb.Message.getWrapperField(this, pkg_api_v1_inventories_delivery_message_pb.Delivery, 5));
};


/**
 * @param {?proto.v1.inventories.Delivery|undefined} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
*/
proto.v1.inventories.DeliveryReturn.prototype.setDelivery = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.clearDelivery = function() {
  return this.setDelivery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v1.inventories.DeliveryReturn.prototype.hasDelivery = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string code = 6;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string return_date = 7;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getReturnDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setReturnDate = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string remark = 8;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getRemark = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setRemark = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string created_at = 9;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getCreatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setCreatedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string created_by = 10;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getCreatedBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setCreatedBy = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string updated_at = 11;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getUpdatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string updated_by = 12;
 * @return {string}
 */
proto.v1.inventories.DeliveryReturn.prototype.getUpdatedBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.setUpdatedBy = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * repeated DeliveryReturnDetail details = 13;
 * @return {!Array<!proto.v1.inventories.DeliveryReturnDetail>}
 */
proto.v1.inventories.DeliveryReturn.prototype.getDetailsList = function() {
  return /** @type{!Array<!proto.v1.inventories.DeliveryReturnDetail>} */ (
    jspb.Message.getRepeatedWrapperField(this, pkg_api_v1_inventories_delivery_return_detail_message_pb.DeliveryReturnDetail, 13));
};


/**
 * @param {!Array<!proto.v1.inventories.DeliveryReturnDetail>} value
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
*/
proto.v1.inventories.DeliveryReturn.prototype.setDetailsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.v1.inventories.DeliveryReturnDetail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.v1.inventories.DeliveryReturnDetail}
 */
proto.v1.inventories.DeliveryReturn.prototype.addDetails = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.v1.inventories.DeliveryReturnDetail, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v1.inventories.DeliveryReturn} returns this
 */
proto.v1.inventories.DeliveryReturn.prototype.clearDetailsList = function() {
  return this.setDetailsList([]);
};


goog.object.extend(exports, proto.v1.inventories);
